# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'flixter_unit1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for flixter_unit1
  pod "AlamofireImage"

  target 'flixter_unit1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'flixter_unit1UITests' do
    # Pods for testing
  end

end
